/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as MarketRouteRouteImport } from './routes/market/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorageIndexRouteImport } from './routes/storage/index'
import { Route as StorageChannelsRouteImport } from './routes/storage/channels'
import { Route as StorageActivityRouteImport } from './routes/storage/activity'
import { Route as MarketStickersRouteImport } from './routes/market/stickers'
import { Route as MarketGiftsRouteImport } from './routes/market/gifts'
import { Route as MarketChannelsRouteImport } from './routes/market/channels'
import { Route as MarketCartRouteImport } from './routes/market/cart'
import { Route as walletWalletRouteImport } from './routes/(wallet)/wallet'
import { Route as StorageOffersReceivedRouteImport } from './routes/storage/offers/received'
import { Route as StorageOffersPlacedRouteImport } from './routes/storage/offers/placed'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRouteRoute = MarketRouteRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageIndexRoute = StorageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorageRoute,
} as any)
const StorageChannelsRoute = StorageChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => StorageRoute,
} as any)
const StorageActivityRoute = StorageActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => StorageRoute,
} as any)
const MarketStickersRoute = MarketStickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => MarketRouteRoute,
} as any)
const MarketGiftsRoute = MarketGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => MarketRouteRoute,
} as any)
const MarketChannelsRoute = MarketChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => MarketRouteRoute,
} as any)
const MarketCartRoute = MarketCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MarketRouteRoute,
} as any)
const walletWalletRoute = walletWalletRouteImport.update({
  id: '/(wallet)/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageOffersReceivedRoute = StorageOffersReceivedRouteImport.update({
  id: '/offers/received',
  path: '/offers/received',
  getParentRoute: () => StorageRoute,
} as any)
const StorageOffersPlacedRoute = StorageOffersPlacedRouteImport.update({
  id: '/offers/placed',
  path: '/offers/placed',
  getParentRoute: () => StorageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market': typeof MarketRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/profile': typeof ProfileRoute
  '/storage': typeof StorageRouteWithChildren
  '/wallet': typeof walletWalletRoute
  '/market/cart': typeof MarketCartRoute
  '/market/channels': typeof MarketChannelsRoute
  '/market/gifts': typeof MarketGiftsRoute
  '/market/stickers': typeof MarketStickersRoute
  '/storage/activity': typeof StorageActivityRoute
  '/storage/channels': typeof StorageChannelsRoute
  '/storage/': typeof StorageIndexRoute
  '/storage/offers/placed': typeof StorageOffersPlacedRoute
  '/storage/offers/received': typeof StorageOffersReceivedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market': typeof MarketRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof walletWalletRoute
  '/market/cart': typeof MarketCartRoute
  '/market/channels': typeof MarketChannelsRoute
  '/market/gifts': typeof MarketGiftsRoute
  '/market/stickers': typeof MarketStickersRoute
  '/storage/activity': typeof StorageActivityRoute
  '/storage/channels': typeof StorageChannelsRoute
  '/storage': typeof StorageIndexRoute
  '/storage/offers/placed': typeof StorageOffersPlacedRoute
  '/storage/offers/received': typeof StorageOffersReceivedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/market': typeof MarketRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/profile': typeof ProfileRoute
  '/storage': typeof StorageRouteWithChildren
  '/(wallet)/wallet': typeof walletWalletRoute
  '/market/cart': typeof MarketCartRoute
  '/market/channels': typeof MarketChannelsRoute
  '/market/gifts': typeof MarketGiftsRoute
  '/market/stickers': typeof MarketStickersRoute
  '/storage/activity': typeof StorageActivityRoute
  '/storage/channels': typeof StorageChannelsRoute
  '/storage/': typeof StorageIndexRoute
  '/storage/offers/placed': typeof StorageOffersPlacedRoute
  '/storage/offers/received': typeof StorageOffersReceivedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/market'
    | '/activity'
    | '/profile'
    | '/storage'
    | '/wallet'
    | '/market/cart'
    | '/market/channels'
    | '/market/gifts'
    | '/market/stickers'
    | '/storage/activity'
    | '/storage/channels'
    | '/storage/'
    | '/storage/offers/placed'
    | '/storage/offers/received'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/market'
    | '/activity'
    | '/profile'
    | '/wallet'
    | '/market/cart'
    | '/market/channels'
    | '/market/gifts'
    | '/market/stickers'
    | '/storage/activity'
    | '/storage/channels'
    | '/storage'
    | '/storage/offers/placed'
    | '/storage/offers/received'
  id:
    | '__root__'
    | '/'
    | '/market'
    | '/activity'
    | '/profile'
    | '/storage'
    | '/(wallet)/wallet'
    | '/market/cart'
    | '/market/channels'
    | '/market/gifts'
    | '/market/stickers'
    | '/storage/activity'
    | '/storage/channels'
    | '/storage/'
    | '/storage/offers/placed'
    | '/storage/offers/received'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketRouteRoute: typeof MarketRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  ProfileRoute: typeof ProfileRoute
  StorageRoute: typeof StorageRouteWithChildren
  walletWalletRoute: typeof walletWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/': {
      id: '/storage/'
      path: '/'
      fullPath: '/storage/'
      preLoaderRoute: typeof StorageIndexRouteImport
      parentRoute: typeof StorageRoute
    }
    '/storage/channels': {
      id: '/storage/channels'
      path: '/channels'
      fullPath: '/storage/channels'
      preLoaderRoute: typeof StorageChannelsRouteImport
      parentRoute: typeof StorageRoute
    }
    '/storage/activity': {
      id: '/storage/activity'
      path: '/activity'
      fullPath: '/storage/activity'
      preLoaderRoute: typeof StorageActivityRouteImport
      parentRoute: typeof StorageRoute
    }
    '/market/stickers': {
      id: '/market/stickers'
      path: '/stickers'
      fullPath: '/market/stickers'
      preLoaderRoute: typeof MarketStickersRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/market/gifts': {
      id: '/market/gifts'
      path: '/gifts'
      fullPath: '/market/gifts'
      preLoaderRoute: typeof MarketGiftsRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/market/channels': {
      id: '/market/channels'
      path: '/channels'
      fullPath: '/market/channels'
      preLoaderRoute: typeof MarketChannelsRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/market/cart': {
      id: '/market/cart'
      path: '/cart'
      fullPath: '/market/cart'
      preLoaderRoute: typeof MarketCartRouteImport
      parentRoute: typeof MarketRouteRoute
    }
    '/(wallet)/wallet': {
      id: '/(wallet)/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof walletWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/offers/received': {
      id: '/storage/offers/received'
      path: '/offers/received'
      fullPath: '/storage/offers/received'
      preLoaderRoute: typeof StorageOffersReceivedRouteImport
      parentRoute: typeof StorageRoute
    }
    '/storage/offers/placed': {
      id: '/storage/offers/placed'
      path: '/offers/placed'
      fullPath: '/storage/offers/placed'
      preLoaderRoute: typeof StorageOffersPlacedRouteImport
      parentRoute: typeof StorageRoute
    }
  }
}

interface MarketRouteRouteChildren {
  MarketCartRoute: typeof MarketCartRoute
  MarketChannelsRoute: typeof MarketChannelsRoute
  MarketGiftsRoute: typeof MarketGiftsRoute
  MarketStickersRoute: typeof MarketStickersRoute
}

const MarketRouteRouteChildren: MarketRouteRouteChildren = {
  MarketCartRoute: MarketCartRoute,
  MarketChannelsRoute: MarketChannelsRoute,
  MarketGiftsRoute: MarketGiftsRoute,
  MarketStickersRoute: MarketStickersRoute,
}

const MarketRouteRouteWithChildren = MarketRouteRoute._addFileChildren(
  MarketRouteRouteChildren,
)

interface StorageRouteChildren {
  StorageActivityRoute: typeof StorageActivityRoute
  StorageChannelsRoute: typeof StorageChannelsRoute
  StorageIndexRoute: typeof StorageIndexRoute
  StorageOffersPlacedRoute: typeof StorageOffersPlacedRoute
  StorageOffersReceivedRoute: typeof StorageOffersReceivedRoute
}

const StorageRouteChildren: StorageRouteChildren = {
  StorageActivityRoute: StorageActivityRoute,
  StorageChannelsRoute: StorageChannelsRoute,
  StorageIndexRoute: StorageIndexRoute,
  StorageOffersPlacedRoute: StorageOffersPlacedRoute,
  StorageOffersReceivedRoute: StorageOffersReceivedRoute,
}

const StorageRouteWithChildren =
  StorageRoute._addFileChildren(StorageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketRouteRoute: MarketRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  ProfileRoute: ProfileRoute,
  StorageRoute: StorageRouteWithChildren,
  walletWalletRoute: walletWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
